add_test( MOV.RegisterToRegister /home/jordan/Documents/schoolwork/CS467/8080/debug/Tests [==[--gtest_filter=MOV.RegisterToRegister]==] --gtest_also_run_disabled_tests)
set_tests_properties( MOV.RegisterToRegister PROPERTIES WORKING_DIRECTORY /home/jordan/Documents/schoolwork/CS467/8080/debug SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test( MOV.RegisterToMem /home/jordan/Documents/schoolwork/CS467/8080/debug/Tests [==[--gtest_filter=MOV.RegisterToMem]==] --gtest_also_run_disabled_tests)
set_tests_properties( MOV.RegisterToMem PROPERTIES WORKING_DIRECTORY /home/jordan/Documents/schoolwork/CS467/8080/debug SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test( XCHG.All /home/jordan/Documents/schoolwork/CS467/8080/debug/Tests [==[--gtest_filter=XCHG.All]==] --gtest_also_run_disabled_tests)
set_tests_properties( XCHG.All PROPERTIES WORKING_DIRECTORY /home/jordan/Documents/schoolwork/CS467/8080/debug SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test( POP.B_D_H_PSW /home/jordan/Documents/schoolwork/CS467/8080/debug/Tests [==[--gtest_filter=POP.B_D_H_PSW]==] --gtest_also_run_disabled_tests)
set_tests_properties( POP.B_D_H_PSW PROPERTIES WORKING_DIRECTORY /home/jordan/Documents/schoolwork/CS467/8080/debug SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test( NOP.All /home/jordan/Documents/schoolwork/CS467/8080/debug/Tests [==[--gtest_filter=NOP.All]==] --gtest_also_run_disabled_tests)
set_tests_properties( NOP.All PROPERTIES WORKING_DIRECTORY /home/jordan/Documents/schoolwork/CS467/8080/debug SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test( XTHL.all /home/jordan/Documents/schoolwork/CS467/8080/debug/Tests [==[--gtest_filter=XTHL.all]==] --gtest_also_run_disabled_tests)
set_tests_properties( XTHL.all PROPERTIES WORKING_DIRECTORY /home/jordan/Documents/schoolwork/CS467/8080/debug SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test( JMP.All /home/jordan/Documents/schoolwork/CS467/8080/debug/Tests [==[--gtest_filter=JMP.All]==] --gtest_also_run_disabled_tests)
set_tests_properties( JMP.All PROPERTIES WORKING_DIRECTORY /home/jordan/Documents/schoolwork/CS467/8080/debug SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
set( Tests_TESTS MOV.RegisterToRegister MOV.RegisterToMem XCHG.All POP.B_D_H_PSW NOP.All XTHL.all JMP.All)
