name: style-enforcement

on:
  push:
    branches:
      - master
      - main
  pull_request:
    branches:
      - master
      - main
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: DoozyX/clang-format-lint-action@v0.10
      with:
        source: './src ./include ./test'
        exclude: ''
        extensions: 'h,cpp,c'
        clangFormatVersion: 11
        style: file

